language: python
python:
  - "3.6"
  - "3.7"
branches:
  only:
    - main
services: redis-server
cache: pip
install: make init
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
